# Generated by Django 3.2.6 on 2021-10-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
